name: kdiskmark
version: '2.0.0'
summary: A simple open-source disk benchmark tool for Linux distros
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
license: GPL-3.0
base: core18

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  kdiskmark:
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-snaps:
      - cmake
      - kde-frameworks-5-core18
      - kde-frameworks-5-core18-sdk
    build-packages:
      - qttools5-dev
      - qttools5-dev-tools # Qt5LinguistTools
      - extra-cmake-modules
    stage-packages:
      - fio
      - libdouble-conversion1
      - libfreetype6
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libharfbuzz0b
      - libicu60
      - libpng16-16
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
    organize:
      usr/share/qt5/translations/*.qm: usr/share/kdiskmark/translations/
    source: https://github.com/JonMagon/KDiskMark.git
    source-tag: 2.0.0

apps:
  kdiskmark:
    adapter: none
    command: usr/bin/kdiskmark

